name: DotNetTemplates-CI

on:
#  push:
#    branches-ignore:
#      - "dependabot/**"
#  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: '6.0.x'
      
    - name: Restore dependencies
      run: dotnet restore GoC.WebTemplate.sln

    - name: Create SNK
      # Creates SNK file from repository variable (created key is not meant for deployment)
      run: |
        [IO.File]::WriteAllBytes("GoC.WebTemplate.snk", [System.Convert]::FromBase64String("${{ secrets.CI_SIGNING_KEY_SNK }}"))

    - name: Build Solution
      # Creates a throw-away SNK file before build (not meant for deployment)
      run: msbuild GoC.WebTemplate.sln /p:Configuration=Release

#    - name: Build
#      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
