name: DotNetTemplates-CI

on:
#  push:
#    branches-ignore:
#      - "dependabot/**"
#  pull_request:
  workflow_dispatch:

jobs:
  build:

    #NOTE: windows-latest (VS2022 as of this writing) does NOT work as long as we target .NET Framework 4.6.1
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      with:
        nuget-version: '6.0.x'
      
    - name: Restore dependencies
      # Note that is "nuget restore" and not "dotnet restore" (for now)
      run: nuget restore GoC.WebTemplate.sln -NonInteractive -Verbosity normal

    - name: Create SNK
      # Creates SNK file from repository variable (created key is not meant for deployment)
      run: |
        [IO.File]::WriteAllBytes("GoC.WebTemplate.snk", [System.Convert]::FromBase64String("${{ secrets.CI_SIGNING_KEY_SNK }}"))

    - name: Build Solution
      run: msbuild GoC.WebTemplate.sln /p:Configuration=Release

    - name: Test Components
      run: dotnet test Components.Tests --no-build --verbosity normal

    - name: Test Components.Core
      run: dotnet test Components.Core.Tests --no-build --verbosity normal

    - name: Test Components.Framework
      run: |
        & packages\xunit.runner.console.2.4.1\tools\net461\xunit.console.exe Components.Framework.Tests\bin\Release\GoC.WebTemplate.Components.Framework.Tests.dll

#    - name: Build
#      run: dotnet build --no-restore
#    - name: Test
#      run: dotnet test --no-build --verbosity normal
